/** @type {import('tailwindcss').Config} */ module.exports = {
  content: ['./src/**/*.{html,jsx}'],
  theme: {
    borderWidth: {
      DEFAULT: '2px',
      0: '0',
      2: '2px',
      4: '4px',
      6: '6px',
      8: '8px',
    },
    extend: {
      gridTemplateRows: { layout: 'h-min 1fr' },
      fontFamily: {
        // sans: ['TS Riccione'],
        // mono: ['TS Riccione'],
        // emoji: ['Segoe UI Emoji'],
        // sans: ['Forma DJR Micro'],
        sans: ['Forma DJR Micro'],
        mono: ['IBM Plex Mono'],
        emoji: ['Segoe UI Emoji'],
      },
      fontSize: {
        xs: [
          '0.75rem',
          {
            lineHeight: '0.94rem',
          },
        ],
        sm: [
          '0.875rem',
          {
            lineHeight: '1.1rem',
          },
        ],
        base: [
          '1rem',
          {
            lineHeight: '1.25rem',
            letterSpacing: '-0.02rem',
          },
        ],
        lg: [
          '1.125rem',
          {
            lineHeight: '1.4rem',
            letterSpacing: '-0.02rem',
          },
        ],
        xl: [
          '1.25rem',
          {
            lineHeight: '1.56rem',
            letterSpacing: '-0.02rem',
          },
        ],
        '2xl': [
          '1.5rem',
          {
            lineHeight: '1.875rem',
            letterSpacing: '-0.02rem',
          },
        ],
        '3xl': [
          '1.875rem',
          {
            lineHeight: '1.875rem',
            letterSpacing: '-0.02rem',
          },
        ],
        '4xl': [
          '2.1rem',
          {
            lineHeight: '2.1rem',
            // letterSpacing: '-0.05rem',
          },
        ],
      },
      spacing: {
        2: '.5rem',
      },
    },
  },
  daisyui: {
    themes: [
      {
        'IBM Carbon': {
          primary: '#0043ce',
          'primary-content': '#fff',
          secondary: '#393939',
          'secondary-content': '#fff',
          neutral: '#393939',
          'neutral-content': '#fff',
          success: '#24a148',
          'success-content': '#fff',
          warning: '#ff832b',
          'warning-content': '#fff',
          error: '#da1e28',
          'error-content': '#fff',
          '--rounded-box': '0rem',
          '--rounded-btn': '0rem',
          '--rounded-badge': '0rem',
          '--animation-btn': '0s',
          '--animation-input': '0s',
          '--btn-text-case': 'uppercase',
          '--navbar-padding': '0rem',
          '--border-btn': '0px',
          'base-100': '#ffffff',
          'base-200': '#f4f4f4',
          'base-300': '#ffffff',
          'base-content': '#000',
        },
      },
      {
        Carbon: {
          primary: '#0043ce',
          'primary-content': '#fff',
          secondary: '#262626',
          'secondary-content': '#fff',
          neutral: '#262626',
          'neutral-content': '#fff',
          success: '#24a148',
          'success-content': '#fff',
          warning: '#ff832b',
          'warning-content': '#fff',
          error: '#da1e28',
          'error-content': '#fff',
          '--rounded-box': '0rem',
          '--rounded-btn': '0rem',
          '--rounded-badge': '0rem',
          '--animation-btn': '0s',
          '--animation-input': '0s',
          '--btn-text-case': 'uppercase',
          '--navbar-padding': '0rem',
          '--border-btn': '0px',
          'base-100': '#161616',
          'base-200': '#262626',
          'base-content': '#fff',
        },
      },
      {
        summer: {
          primary: '#51A1F8',
          'primary-content': '#000',
          secondary: '#c9d6dc',
          'secondary-content': '#000',
          neutral: '#8eced4',
          'neutral-content': '#000',
          success: '#5ECC7B',
          'success-content': '#000',
          warning: '#E68E33',
          'warning-content': '#000',
          error: '#FF5E4D',
          'error-content': '#000',
          '--rounded-box': '0.25rem',
          '--rounded-btn': '0.125rem',
          '--rounded-badge': '0rem',
          '--animation-btn': '0s',
          '--animation-input': '0s',
          '--btn-text-case': 'uppercase',
          '--navbar-padding': '0rem',
          '--border-btn': '0px',
          'base-100': '#fff',
          'base-content': '#000',
        },
      },
      {
        emerald: {
          primary: '#51A1F8',
          'primary-content': '#000',
          secondary: '#F8E268',
          'secondary-content': '#000',
          neutral: '#D3D3D7',
          'neutral-content': '#000',
          success: '#5ECC7B',
          'success-content': '#000',
          warning: '#E68E33',
          'warning-content': '#000',
          error: '#FF5E4D',
          'error-content': '#000',
          '--rounded-box': '0rem',
          '--rounded-btn': '0rem',
          '--rounded-badge': '0rem',
          '--animation-btn': '0s',
          '--animation-input': '0s',
          '--btn-text-case': 'uppercase',
          '--navbar-padding': '0rem',
          '--border-btn': '0px',
          'base-100': '#f4eddd',
          'base-content': '#000',
        },
      },

      {
        teddys: {
          primary: '#115e59',
          'primary-content': '#fff',
          secondary: '#ff7e00',
          'secondary-content': '#fff',
          neutral: '#1f2937',
          'neutral-content': '#fff',
          'base-100': '#fff',
          success: '#16a34a',
          'success-content': '#fff',
          warning: '#ff7e00',
          'warning-content': '#fff',
          error: '#b91c1c',
          'error-content': '#fff',
          '--rounded-box': '0.5rem',
          '--rounded-btn': '0.25rem',
          '--rounded-badge': '0.5rem',
          '--animation-btn': '0s',
          '--animation-input': '0s',
          '--btn-text-case': 'uppercase',
          '--navbar-padding': '.5rem',
          '--border-btn': '0px',
        },
      },
      'corporate',
      'retro',
      'cyberpunk',
      'night',
    ],
    logs: false,
  },
  plugins: [require('daisyui')],
  darkMode: 'class',
};
